### ISSUE TITLE
Query : Is it possible to use HTTPClientFactory in ASP.NET core 2.0 ?

### ISSUE THREAD

**Issue by madhub** [RehanSaeed/HttpClientSample#2]
Read your blog post on using `HTTPClientFactory ` in ASP.NET core 2.1 ,  Is it possible to use `HTTPClientFactory ` in ASP.NET core 2.0 ?.

**Comment by slang25** [comment]
@madhub Hi, yes it can. The types [live here](https://www.nuget.org/packages/Microsoft.Extensions.Http/) which targets netstandard1.6, which will work with .NET Core 2.0. I've tried this sample downgraded and it works.

**Comment by RehanSaeed** [comment]
@slang25 Interesting, thats pretty cool.
